from typing import (
    Union, Iterable, Sequence, List, Tuple, 
    Optional, TypeAlias, Self, Any, overload
)

Numeric: TypeAlias = Union[int, float]

CoordinateLike: TypeAlias = Sequence[Numeric]
RectLike: TypeAlias = Sequence[Numeric]

ColorLike = Sequence[Numeric]

class Coordinate(List[Numeric]):
    @overload
    def __new__(cls, x: Numeric, y: Numeric) -> Self: ...
    @overload
    def __new__(cls, pos: CoordinateLike, /) -> Self: ...
    def __new__(cls, x: Union[Numeric, CoordinateLike], y: Optional[Numeric] = None) -> Self: ...
    @property
    def xy(self) -> Tuple[Numeric, Numeric]: ...
    @xy.setter
    def xy(self, value: CoordinateLike) -> None: ...
    @property
    def x(self) -> Numeric: ...
    @x.setter
    def x(self, value: Numeric) -> None: ...
    @property
    def y(self) -> Numeric: ...
    @y.setter
    def y(self) -> Numeric: ...
    def magnitude(self) -> float: ...
    def normalize(self) -> Self: ...
    def length(self) -> float: ...
    def distance(self, other: CoordinateLike) -> float: ...
    def dot(self, other: CoordinateLike) -> float: ...
    def cross(self, other: CoordinateLike) -> float: ...
    def cross_scalar(self, scalar: float) -> Self: ...
    def __add__(self, other: CoordinateLike) -> Self: ...
    def __radd__(self, other: CoordinateLike) -> Self: ...
    def __iadd__(self, other: CoordinateLike) -> Self: ...
    def __sub__(self, other: CoordinateLike) -> Self: ...
    def __rsub__(self, other: CoordinateLike) -> Self: ...
    def __isub__(self, other: CoordinateLike) -> Self: ...
    def __mul__(self, other: Numeric) -> Self: ...
    def __rmul__(self, other: Numeric) -> Self: ...
    def __imul__(self, other: Numeric) -> Self: ...
    def __truediv__(self, other: Numeric) -> Self: ...
    def __rtruediv__(self, other: Numeric) -> Self: ...
    def __itruediv__(self, other: Numeric) -> Self: ...
    def __floordiv__(self, other: Numeric) -> Self: ...
    def __rfloordiv__(self, other: Numeric) -> Self: ...
    def __ifloordiv__(self, other: Numeric) -> Self: ...
    def __mod__(self, other: Numeric) -> Self: ...
    def __rmod__(self, other: Numeric) -> Self: ...
    def __imod__(self, other: Numeric) -> Self: ...
    def __pow__(self, other: Numeric) -> Self: ...
    def __rpow__(self, other: Numeric) -> Self: ...
    def __ipow__(self, other: Numeric) -> Self: ...
    def __neg__(self) -> Self: ...
    def __pos__(self) -> Self: ...
    def __abs__(self) -> Self: ...
    def __round__(self, n: Optional[int] = None) -> Self: ...
    def __getnewargs__(self) -> Tuple[float, float]: ...
    def __repr__(self) -> str: ...

Vec2D: TypeAlias = Coordinate
Point: TypeAlias = Coordinate
Position: TypeAlias = Coordinate
Pos: TypeAlias = Coordinate
Vector: TypeAlias = Coordinate

class CoordinateList(List[Coordinate]):
    @overload
    def __init__(self, *args: CoordinateLike) -> None: ...
    @overload
    def __init__(self, *, coordinates: Iterable[CoordinateLike]) -> None: ...
    def __init__(self, *args: CoordinateLike, coordinates: Optional[Iterable[CoordinateLike]] = None) -> None: ...
    def __contains__(self, item: CoordinateLike) -> bool: ...
    def append(self, item: CoordinateLike) -> None: ...
    def remove(self, item: CoordinateLike) -> None: ...
    def index(self, item: CoordinateLike) -> int: ...
    def count(self, item: CoordinateLike) -> int: ...
    def insert(self, index: int, item: CoordinateLike) -> None: ...
    def extend(self, iterable: Iterable[CoordinateLike]) -> None: ...
    def copy(self) -> Self: ...

Vec2DList: TypeAlias = CoordinateList
PointList: TypeAlias = CoordinateList
PositionList: TypeAlias = CoordinateList
PosList: TypeAlias = CoordinateList
Vertices: TypeAlias = CoordinateList

class Lines(CoordinateList):
    @property
    def start(self) -> Coordinate: ...
    @property
    def end(self) -> Coordinate: ...

class Rect(RectLike):
    @overload
    def __init__(self, x: Numeric, y: Numeric, width: Numeric, height: Numeric) -> None: ...
    @overload
    def __init__(self, rectangle: RectLike, /) -> None: ...
    def __init__(self, x: Union[Numeric, RectLike], y: Optional[Numeric] = None, width: Optional[Numeric] = None, height: Optional[Numeric] = None) -> None: ...
    @property
    def xy(self) -> Coordinate: ...
    @xy.setter
    def xy(self, value: Coordinate) -> None: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, value: float) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, value: float) -> None: ...
    @property
    def vertices(self) -> CoordinateList: ...
    @property
    def edges(self) -> CoordinateList: ... 
    @property
    def width(self) -> float: ...
    @width.setter
    def width(self, value: float) -> None: ...
    @property
    def height(self) -> float: ...
    @height.setter
    def height(self, value: float) -> None: ...
    @property
    def size(self) -> Coordinate: ...
    @size.setter
    def size(self, value: CoordinateLike) -> None: ...
    @property
    def top(self) -> float: ...
    @top.setter
    def top(self, value: float) -> None: ...
    @property
    def bottom(self) -> float: ...
    @bottom.setter
    def bottom(self, value: float) -> None: ...
    @property
    def left(self) -> float: ...
    @left.setter
    def left(self, value: float) -> None: ...
    @property
    def right(self) -> float: ...
    @right.setter
    def right(self, value: float) -> None: ...
    @property
    def topleft(self) -> Coordinate: ...
    @topleft.setter
    def topleft(self, value: CoordinateLike) -> None: ...
    @property
    def bottomleft(self) -> Coordinate: ...
    @bottomleft.setter
    def bottomleft(self, value: CoordinateLike) -> None: ...
    @property
    def topright(self) -> Coordinate: ...
    @topright.setter
    def topright(self, value: CoordinateLike) -> None: ...
    @property
    def bottomright(self) -> Coordinate: ...
    @bottomright.setter
    def bottomright(self, value: CoordinateLike) -> None: ...
    @property
    def center(self) -> Coordinate: ...
    @center.setter
    def center(self, value: CoordinateLike) -> None: ...
    @property
    def centerleft(self) -> Coordinate: ...
    @centerleft.setter
    def centerleft(self, value: CoordinateLike) -> None: ...
    @property
    def centerright(self) -> Coordinate: ...
    @centerright.setter
    def centerright(self, value: CoordinateLike) -> None: ...
    @property
    def centertop(self) -> Coordinate: ...
    @centertop.setter
    def centertop(self, value: CoordinateLike) -> None: ...
    @property
    def centerbottom(self) -> Coordinate: ...
    @centerbottom.setter
    def centerbottom(self, value: CoordinateLike) -> None: ...
    @property
    def area(self) -> float: ...
    @property
    def circumference(self) -> float: ...
    @property
    def position(self) -> Coordinate: ...
    @position.setter
    def position(self, value: CoordinateLike) -> None: ...
    @overload
    def move(self, dx: Numeric, dy: Numeric) -> None: ...
    @overload
    def move(self, delta: CoordinateLike, /) -> None: ...
    def move(self, dx: Union[Numeric, CoordinateLike], dy: Optional[Numeric] = None) -> None: ...
    @overload
    def translate(self, dx: Numeric, dy: Numeric) -> None: ...
    @overload
    def translate(self, delta: CoordinateLike, /) -> None: ...
    def translate(self, dx: Union[Numeric, CoordinateLike], dy: Optional[Numeric] = None) -> None: ...
    @overload
    def scale(self, dw: Numeric, dh: Numeric) -> None: ...
    @overload
    def scale(self, delta: CoordinateLike, /) -> None: ...
    def scale(self, dw: Union[Numeric, CoordinateLike], dh: Optional[Numeric] = None) -> None: ...
    def contains(self, other: Union[Self, RectLike, Coordinate, CoordinateLike]) -> bool: ...
    def intersects(self, other: Union[Self, RectLike, Coordinate, CoordinateLike]) -> bool: ...
    def distance(self, other: Union[Self, RectLike, Coordinate, CoordinateLike]) -> float: ...
    def __getitem__(self, index: int) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterable[Numeric]: ...
    def __repr__(self) -> str: ...

Rectangle: TypeAlias = Rect

class Square(Rect):
    @overload
    def __init__(self, x: Numeric, y: Numeric, width: Numeric, height: Optional[Numeric] = None) -> None: ...
    @overload
    def __init__(self, x: Numeric, y: Numeric, size: Numeric) -> None: ...
    @overload
    def __init__(self, rectangle: RectLike, /) -> None: ...
    def __init__(self, x: Union[Numeric, RectLike], y: Optional[Numeric] = None, width: Optional[Numeric] = None, height: Optional[Numeric] = None, *, size: Optional[Numeric] = None) -> None: ...

class Surface(List[List[Any]]):
    def __init__(self) -> None: ...
    def __getitem__(self, index: Union[int, Tuple[int, int]]) -> Union[List, Any]: ...
    def __setitem__(self, index: Union[int, Tuple[int, int]], value: Any) -> None: ...
    @overload
    def setup(self, x: int, y: int) -> None: ...
    @overload
    def setup(self, size: Sequence[int], /) -> None: ...
    def setup(self, x: Union[int, Sequence[int]], y: Optional[int] = None) -> None: ...
    def blit(self, surface: Self, pos: Union[Rect, RectLike, Coordinate, CoordinateLike]) -> None: ...
    def fill(self, value: Any) -> None: ...
    def clear(self) -> None: ...
    def reset(self) -> None: ...
    def get_rect(self, **kwargs: Numeric) -> Rect: ...

Map: TypeAlias = Surface

class Color(tuple):
    @overload
    def __new__(cls, r: Numeric, g: Numeric, b: Numeric) -> Self: ...
    @overload
    def __new__(cls, color: ColorLike, /) -> Self: ...
    def __new__(cls, r: Union[Numeric, ColorLike], g: Optional[Numeric] = None, b: Optional[Numeric] = None) -> Self: ...
    @staticmethod
    def unpack(packed: int) -> Self: ...
    @property
    def r(self) -> Numeric: ...
    @property
    def g(self) -> Numeric: ...
    @property
    def b(self) -> Numeric: ...
    def clamp(self) -> Self: ...
    def pack(self) -> int: ...
    def __eq__(self, other: Union[ColorLike, int]) -> bool: ...
    def __ne__(self, other: Union[ColorLike, int]) -> bool: ...
    def __add__(self, other: ColorLike) -> Self: ...
    def __radd__(self, other: ColorLike) -> Self: ...
    def __iadd__(self, other: ColorLike) -> Self: ...
    def __sub__(self, other: ColorLike) -> Self: ...
    def __rsub__(self, other: ColorLike) -> Self: ...
    def __isub__(self, other: ColorLike) -> Self: ...
    def __mul__(self, other: Numeric) -> Self: ...
    def __rmul__(self, other: Numeric) -> Self: ...
    def __imul__(self, other: Numeric) -> Self: ...
    def __truediv__(self, other: Numeric) -> Self: ...
    def __rtruediv__(self, other: Numeric) -> Self: ...
    def __itruediv__(self, other: Numeric) -> Self: ...
    def __floordiv__(self, other: Numeric) -> Self: ...
    def __rfloordiv__(self, other: Numeric) -> Self: ...
    def __ifloordiv__(self, other: Numeric) -> Self: ...
    def __mod__(self, other: Numeric) -> Self: ...
    def __rmod__(self, other: Numeric) -> Self: ...
    def __imod__(self, other: Numeric) -> Self: ...
    def __neg__(self) -> Self: ...
    def __pos__(self) -> Self: ...
    def __abs__(self) -> Self: ...
    def __round__(self, n: Optional[int] = None) -> Self: ...
    def __getnewargs__(self) -> Tuple[Numeric, Numeric, Numeric]: ...
    def __repr__(self) -> str: ...

@overload
def create_rect(x: Numeric, y: Numeric, width: Numeric, height: Numeric, **kwargs: Numeric) -> Rect: ...
@overload
def create_rect(initial_matrix: RectLike, **kwargs: Numeric) -> Rect: ...
def create_rect(x: Union[Numeric, RectLike], y: Optional[Numeric] = None, width: Optional[Numeric] = None, height: Optional[Numeric] = None, **kwargs: Union[Numeric, RectLike]) -> Rect: ...