from typing import (
    Union, Optional, TypeAlias, Any, overload
)
from .core import (
    RectLike, CoordinateLike, Coordinate, 
    Rect, Square, Surface, ColorLike
)

class RectBox(Surface):
    rect: Rect
    @overload
    def __init__(self, x: int, y: int, width: int, height: int, color: Optional[ColorLike] = None, *, setup: bool = True) -> None: ...
    @overload
    def __init__(self, rect: RectLike, color: Optional[ColorLike], *, setup: bool = True) -> None: ...
    def __init__(self, x: Union[int, RectLike], y: Optional[Union[int, ColorLike]] = None, width: Optional[int] = None, height: Optional[int] = None, color: Optional[ColorLike] = None, *, setup: bool = True) -> None: ...
    def set_detail(self, active: bool = False) -> None: ...
    def fill(self, value: Any) -> None: ...
    def clear(self) -> None: ...
    def blit(self, surface: Surface, pos: Optional[Union[Rect, RectLike, Coordinate, CoordinateLike]] = None) -> None: ...

Box: TypeAlias = RectBox

class SquareBox(RectBox):
    rect: Square
    @overload
    def __init__(self, x: int, y: int, width: int, height: int, color: Optional[ColorLike] = None) -> None: ...
    @overload
    def __init__(self, x: int, y: int, size: int, color: Optional[ColorLike] = None) -> None: ...
    @overload
    def __init__(self, rect: RectLike, color: Optional[ColorLike]) -> None: ...
    def __init__(self, x: Union[int, RectLike], y: Optional[Union[int, ColorLike]] = None, width: Optional[int] = None, height: Optional[Union[int, ColorLike]] = None, color: Optional[ColorLike] = None, *, size: Optional[int] = None) -> None: ...

AnyBox: TypeAlias = Union[RectBox, SquareBox]