from typing import Set, Tuple, Dict, Any
from .core import Numeric, Rect

class SpatialGrid:
    cell_size: int
    grid_width: int
    grid_height: int
    cells: Dict[Tuple[Numeric, Numeric], Any]

    def __init__(self, cell_size: int, width: int, height: int) -> None: ...
    def _get_cell_coords(self, rect: Rect) -> None: ...
    def add_object(self, obj: Any, rect: Rect) -> None: ...
    def remove_object(self, obj: Any, rect: Rect) -> None: ...
    def get_nearby_objects(self, rect: Rect) -> Set[Any]: ...
    def update(self, obj: Any, new_rect: Rect) -> None: ...